### ISSUE TITLE
to discuss 

### ISSUE THREAD

**Issue by thefux** [rincewound/picopi32#4]
Ich bin mit der Architektur noch nicht sicher, die Idee soweit ist:
Es gibt folgende Teile:
* Entity
* EntitytManager: hier werden alle Entities behandlet, für das erst sind es nur Hero und Monster (entpricht müssen ja bewegt werden, etc...)
* MapManager: anhand der Position  von Entities und die Commandos die er sieht (z.B keyUp, keyDonw, etc ...) kann er entscheiden was passieren soll.

Die Fragen:
* wie werden die Signale hoch kommen, sprich wie kommt das hier ein KeyUp action, sodass das Entity sich bewegt ?
* wer entscheidet, ob das Spiel fertig ist ?
* wie kommunizieren beide Cores, so das wir auf dem Screen was sehen (static buffer ?) ?
* etc ...

sollen wir es ähnlich machen,
https://github.com/rp-rs/pico-blink-rs

und drumherum was basteln ?

**Comment by rincewound** [comment]
Für Grafik: Siehe den branch "HiRes Core", da ist schon ziemlich viel geschrieben
